"""Radarr condensed action-routed MCP tool.

CONCEPT:AU-ECO.mcp.tool-mode-standardization — gitlab-style organized per-service tool surface.
"""

from typing import Any, Literal

from agent_utilities.mcp.action_dispatch import dispatch_async, parse_json_object
from fastmcp import Context, FastMCP
from pydantic import Field

from arr_mcp.auth import get_radarr_client

_RADARR_ACTIONS = Literal[
    "add_movie",
    "delete_autotagging_id",
    "delete_blocklist_bulk",
    "delete_blocklist_id",
    "delete_command_id",
    "delete_customfilter_id",
    "delete_customformat_bulk",
    "delete_customformat_id",
    "delete_delayprofile_id",
    "delete_downloadclient_bulk",
    "delete_downloadclient_id",
    "delete_exclusions_bulk",
    "delete_exclusions_id",
    "delete_importlist_bulk",
    "delete_importlist_id",
    "delete_indexer_bulk",
    "delete_indexer_id",
    "delete_metadata_id",
    "delete_movie_editor",
    "delete_movie_id",
    "delete_moviefile_bulk",
    "delete_moviefile_id",
    "delete_notification_id",
    "delete_qualityprofile_id",
    "delete_queue_bulk",
    "delete_queue_id",
    "delete_releaseprofile_id",
    "delete_remotepathmapping_id",
    "delete_rootfolder_id",
    "delete_system_backup_id",
    "delete_tag_id",
    "get_",
    "get_alttitle",
    "get_alttitle_id",
    "get_api",
    "get_autotagging",
    "get_autotagging_id",
    "get_autotagging_schema",
    "get_blocklist",
    "get_blocklist_movie",
    "get_calendar",
    "get_collection",
    "get_collection_id",
    "get_command",
    "get_command_id",
    "get_config_downloadclient",
    "get_config_downloadclient_id",
    "get_config_host",
    "get_config_host_id",
    "get_config_importlist",
    "get_config_importlist_id",
    "get_config_indexer",
    "get_config_indexer_id",
    "get_config_mediamanagement",
    "get_config_mediamanagement_id",
    "get_config_metadata",
    "get_config_metadata_id",
    "get_config_naming",
    "get_config_naming_examples",
    "get_config_naming_id",
    "get_config_ui",
    "get_config_ui_id",
    "get_content_path",
    "get_credit",
    "get_credit_id",
    "get_customfilter",
    "get_customfilter_id",
    "get_customformat",
    "get_customformat_id",
    "get_customformat_schema",
    "get_delayprofile",
    "get_delayprofile_id",
    "get_diskspace",
    "get_downloadclient",
    "get_downloadclient_id",
    "get_downloadclient_schema",
    "get_exclusions",
    "get_exclusions_id",
    "get_exclusions_paged",
    "get_extrafile",
    "get_feed_v3_calendar_radarrics",
    "get_filesystem",
    "get_filesystem_mediafiles",
    "get_filesystem_type",
    "get_health",
    "get_history",
    "get_history_movie",
    "get_history_since",
    "get_importlist",
    "get_importlist_id",
    "get_importlist_movie",
    "get_importlist_schema",
    "get_indexer",
    "get_indexer_id",
    "get_indexer_schema",
    "get_indexerflag",
    "get_language",
    "get_language_id",
    "get_localization",
    "get_localization_language",
    "get_log",
    "get_log_file",
    "get_log_file_filename",
    "get_log_file_update",
    "get_log_file_update_filename",
    "get_login",
    "get_logout",
    "get_manualimport",
    "get_mediacover_movie_id_filename",
    "get_metadata",
    "get_metadata_id",
    "get_metadata_schema",
    "get_movie",
    "get_movie_id",
    "get_movie_id_folder",
    "get_movie_lookup",
    "get_movie_lookup_imdb",
    "get_movie_lookup_tmdb",
    "get_moviefile",
    "get_moviefile_id",
    "get_notification",
    "get_notification_id",
    "get_notification_schema",
    "get_parse",
    "get_path",
    "get_ping",
    "get_qualitydefinition",
    "get_qualitydefinition_id",
    "get_qualitydefinition_limits",
    "get_qualityprofile",
    "get_qualityprofile_id",
    "get_qualityprofile_schema",
    "get_queue",
    "get_queue_details",
    "get_queue_status",
    "get_release",
    "get_releaseprofile",
    "get_releaseprofile_id",
    "get_remotepathmapping",
    "get_remotepathmapping_id",
    "get_rename",
    "get_rootfolder",
    "get_rootfolder_id",
    "get_system_backup",
    "get_system_routes",
    "get_system_routes_duplicate",
    "get_system_status",
    "get_system_task",
    "get_system_task_id",
    "get_tag",
    "get_tag_detail",
    "get_tag_detail_id",
    "get_tag_id",
    "get_update",
    "get_wanted_cutoff",
    "get_wanted_missing",
    "lookup_movie",
    "post_autotagging",
    "post_command",
    "post_customfilter",
    "post_customformat",
    "post_delayprofile",
    "post_downloadclient",
    "post_downloadclient_action_name",
    "post_downloadclient_test",
    "post_downloadclient_testall",
    "post_exclusions",
    "post_exclusions_bulk",
    "post_history_failed_id",
    "post_importlist",
    "post_importlist_action_name",
    "post_importlist_movie",
    "post_importlist_test",
    "post_importlist_testall",
    "post_indexer",
    "post_indexer_action_name",
    "post_indexer_test",
    "post_indexer_testall",
    "post_login",
    "post_manualimport",
    "post_metadata",
    "post_metadata_action_name",
    "post_metadata_test",
    "post_metadata_testall",
    "post_movie",
    "post_movie_import",
    "post_notification",
    "post_notification_action_name",
    "post_notification_test",
    "post_notification_testall",
    "post_qualityprofile",
    "post_queue_grab_bulk",
    "post_queue_grab_id",
    "post_release",
    "post_release_push",
    "post_releaseprofile",
    "post_remotepathmapping",
    "post_rootfolder",
    "post_system_backup_restore_id",
    "post_system_backup_restore_upload",
    "post_system_restart",
    "post_system_shutdown",
    "post_tag",
    "put_autotagging_id",
    "put_collection",
    "put_collection_id",
    "put_config_downloadclient_id",
    "put_config_host_id",
    "put_config_importlist_id",
    "put_config_indexer_id",
    "put_config_mediamanagement_id",
    "put_config_metadata_id",
    "put_config_naming_id",
    "put_config_ui_id",
    "put_customfilter_id",
    "put_customformat_bulk",
    "put_customformat_id",
    "put_delayprofile_id",
    "put_delayprofile_reorder_id",
    "put_downloadclient_bulk",
    "put_downloadclient_id",
    "put_exclusions_id",
    "put_importlist_bulk",
    "put_importlist_id",
    "put_indexer_bulk",
    "put_indexer_id",
    "put_metadata_id",
    "put_movie_editor",
    "put_movie_id",
    "put_moviefile_bulk",
    "put_moviefile_editor",
    "put_moviefile_id",
    "put_notification_id",
    "put_qualitydefinition_id",
    "put_qualitydefinition_update",
    "put_qualityprofile_id",
    "put_releaseprofile_id",
    "put_remotepathmapping_id",
    "put_tag_id",
]


def register_radarr_tools(mcp: FastMCP) -> None:
    @mcp.tool(tags={"radarr"})
    async def radarr_action(
        action: _RADARR_ACTIONS = Field(
            description="The action/method name to execute on Radarr (get_movie to list all movies, add_movie, get_system_status). One of 239 real Radarr API methods; use action='list_actions' to list them all at runtime."
        ),
        params_json: str = Field(
            default="{}",
            description="JSON string of parameters to pass to the action.",
        ),
        ctx: Context | None = None,
    ) -> Any:
        """Execute any Radarr API action."""
        client = get_radarr_client()
        kwargs = {
            k: v for k, v in parse_json_object(params_json).items() if v is not None
        }
        return await dispatch_async(
            client, action, kwargs, service="arr-radarr", ctx=ctx
        )
